### ISSUE TITLE
Artifactory Maven task does have a Jdk version selection

### ISSUE THREAD

**Issue by uma101** [jfrog/jfrog-azure-devops-extension#161]
Artifactory Maven task doesn’t have a jdk version selection option( drop down ) so it is picking up the default version jdk 8 on the build server. Since we have multiple versions installed on the server(Jdk 8 and Jdk 11).  Is it possible to select different versions of jdk using this task?

**Comment by JasonH74** [comment]
You can use the  `JavaToolInstaller` to set the JDK version.  For Azure  managed  build agents, it has 11 installed, but since 8 is the default you need to tell it to use the installed JDK 11.  This task updates the path and JAVA_HOME to the JDK 11.

```
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '11'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
          cleanDestinationDirectory: false
```
