### ISSUE TITLE
Conan uses a different home directory if the build number is changed during the pipeline

### ISSUE THREAD

**Issue by peter-bloomfield** [jfrog/jfrog-azure-devops-extension#181]
**Describe the bug**
When using the `ArtifactoryConan@1` task, the path of the Conan home directory is based on the pipeline build number. However, the build number gets re-evaluated every time a Conan command is executed. As a result, if the pipeline changes the build number in between Conan tasks then the later tasks use a different home directory. This means Conan no longer has access to the previous configuration or cache.

**To Reproduce**
This pipeline will reproduce the issue on a Microsoft-hosted Windows build agent:

```
jobs:
- job: example

  pool:
    vmImage: vs2017-win2016

  steps:
  - bash: pip3 install conan==1.28.0

  - task: ArtifactoryConan@1
    inputs:
      conanCommand: 'Custom'
      customArguments: 'config set general.revisions_enabled=1'

  - bash: echo "##vso[build.updatebuildnumber]$(Build.BuildNumber)-alpha"

  - task: ArtifactoryConan@1
    inputs:
      conanCommand: 'Custom'
      customArguments: 'config get general.revisions_enabled'

```

In my test pipeline, the default build number was `20200806.4`.

During the second step, the pipeline output reported the Conan home directory like this:

```
Conan User Home: D:\a\254\20200806.4
```

The third step changed the build number to `20200806.4-alpha`.

The fourth step then failed with the following output:

```
Conan User Home: D:\a\254\20200806.4-alpha
...
ERROR: 'revisions_enabled' doesn't exist in [general]
```

The failure occurred because the configuration value was not available. This is because steps 2 and 4 were using different Conan home directories as a result of the changed build number.

The pipeline succeeded if I removed the third step; i.e. if the build number did not change.

**Expected behavior**
I would expect all Conan commands throughout the pipeline to use the same Conan home directory. It should not be affected by changes to the build number.

**Versions**
- Artifactory Azure DevOps extension version: 1.10.0
- Agent operating system: Microsoft-hosted agent - vs2017-win2016
- JFrog Artifactory version: n/a

**Additional context**
I found this issue because I wanted the pipeline build number to include the Conan recipe version. I was able to work around it by updating the build number after all other build steps. It would be helpful to be able to do it at any time though.
