### ISSUE TITLE
Artifactory Nuget Push Fails on Extension Version 1.10.2

### ISSUE THREAD

**Issue by MichaelDenwood** [jfrog/jfrog-azure-devops-extension#184]
**Describe the bug**
Artifactory Nuget Push Fails on Extension Version 1.10.2
invalid character '\x00' looking for beginning of value

**To Reproduce**
Steps to reproduce the behavior
<img width="762" alt="artiissue" src="https://user-images.githubusercontent.com/65730848/90678203-3a625400-e213-11ea-830a-4c35619b689d.PNG">

**Expected behavior**
The package should upload without error.

**Screenshots**
Executing cliCommand: F:\Agents\SaaSProdW1\_work\_tool\jfrog\1.38.4\x64\jfrog.exe rt u F:\\Agents\\SaaSProdW1\\_work\\55\\a\\*.nupkg nuget-hosted-phx --url="https://artifacts.xx.com/artifactory" --user=*** --password=***
[Error] invalid character '\x00' looking for beginning of value

**Versions**
- Artifactory Azure DevOps extension version: 1.10.2 (Seems to only happen in Azure DevOps Cloud.  Works from on on prem instance of Azure DevOps)
- Agent operating system: Windows
- JFrog Artifactory version: 

**Additional context**

**Comment by yahavi** [comment]
Thanks for reporting this issue, @MichaelDenwood!
We couldn't reproduce this issue.
I used the [project-examples](https://github.com/jfrog/project-examples) repository and the following configuration:
```yaml
trigger: none 

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@1
- task: ArtifactoryNuGet@2
  inputs:
    command: 'restore'
    artifactoryService: 'ecosys'
    targetResolveRepo: 'nuget'
    solutionPath: '**/*.sln'
    packagesDirectory: '$(Build.ArtifactStagingDirectory)'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: ArtifactoryNuGet@2
  inputs:
    command: 'push'
    artifactoryService: 'ecosys'
    targetDeployRepo: 'nuget'
    pathToNupkg: '$(Build.ArtifactStagingDirectory)\*.nupkg'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'ecosys'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
```

The Artifactory NuGet push searches for .nupkg files and uploads them by `jfrog rt u` command.
Can you please try, for the experiment, to upload the problematic package using the [jfrog cli](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Azure+DevOps+Extension#ArtifactoryAzureDevOpsExtension-ExecutingJFrogCLICommands) task? Something like this:
```yaml
- task: JfrogCli@1
  inputs:
    artifactoryService: 'ecosys'
    command: 'jfrog rt u F:\Agents\SaaSProdW1\_work\55\a\.nupkg nuget-hosted-phx'
```
Also - it will be very helpful if you could provide a reproducer project with the yaml configuration and the nuget project in GitHub.
